export default {
    GK : [
        {
            id: 1,
            name: 'THIBAUT',
            lastname: 'COURTOIS',
            number: 13,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Courtois',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/BEL',
        },
        {
            id: 2,
            name: 'WILLY',
            lastname: 'CABALLERO',
            number: 1,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Caballero',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/ARG',
        }
    ],
    DF: [
        {
            id: 3,
            name: 'ANTONIO',
            lastname: 'RÜDIGER',
            number: 2,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Rudiger',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/DEU',
        },
        {
            id: 4,
            name: 'Marcos',
            lastname: 'Alonso',
            number: 3,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Alonso',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/ESP',
        },
        {
            id: 5,
            name: 'Victor',
            lastname: 'Moses',
            number: 15,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Moses',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/NGA',
        },
        {
            id: 6,
            name: 'Davide',
            lastname: 'Zappacosta',
            number: 21,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Zappacosta',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/ITA',
        },
        {
            id: 7,
            name: 'Gary',
            lastname: 'Cahill',
            number: 24,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Cahill',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/GBR-ENG',
        },
        {
            id: 8,
            name: 'Andreas',
            lastname: 'Christensen',
            number: 27,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Christensen',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/DNK',
        },
        {
            id: 9,
            name: 'César ',
            lastname: 'Azpilicueta',
            number: 28,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Azpi',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/ESP',
        },
        {
            id: 10,
            name: 'David',
            lastname: 'Luiz',
            number: 30,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Luiz',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/BRA',
        },
        {
            id: 11,
            name: 'Emerson',
            lastname: 'Palmieri',
            number: 33,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Emerson',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/ITA',
        },
        {
            id: 12,
            name: 'Ola',
            lastname: 'Aina',
            number: 34,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/on-loan/2017-18/headshot/Ola-Aina',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/NGA',
        }
    ],
    MD: [
        {
            id: 13,
            name: 'Cesc',
            lastname: 'Fabregas',
            number: 4,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Cesc',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/ESP',
        },
        {
            id: 14,
            name: ' ',
            lastname: 'Jorginho',
            number: 5,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_faces,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/jorginho_proflle_portrait',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/ITA',
        },
        {
            id: 15,
            name: 'Danny',
            lastname: 'Drinkwater',
            number: 6,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Drinkwater',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/GBR-ENG',
        },
        {
            id: 16,
            name: `N'Golo`,
            lastname: 'Kante',
            number: 7,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Kante',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/FRA',
        },
        {
            id: 17,
            name: 'Ross',
            lastname: 'Barkley',
            number: 8,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Barkley',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/GBR-ENG',
        },
        {
            id: 18,
            name: 'Eden',
            lastname: 'Hazard',
            number: 10,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Hazard',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/BEL',
        },
        {
            id: 19,
            name: '',
            lastname: 'Pedro',
            number: 11,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Pedro',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/ESP',
        },
        {
            id: 20,
            name: 'Tiemoué',
            lastname: 'Bakayoko',
            number: 14,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Bakayoko',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/FRA',
        },
        {
            id: 21,
            name: 'Charly',
            lastname: 'Musonda Jr',
            number: 17,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/on-loan/2017-18/headshot/Charly-Musonda-Jr',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/BEL',
        },
        {
            id: 22,
            name: '',
            lastname: 'Willian',
            number: 22,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Willian',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/BRA',
        },
    ],
    FW: [
        {
            id: 23,
            name: 'Álvaro',
            lastname: 'Morata',
            number: 29,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Morata',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/ESP',
        },
        {
            id: 24,
            name: 'Olivier',
            lastname: 'Giroud',
            number: 18,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/first-team/2018-19/portrait/02332_Headshots_1819Giroud',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/FRA',
        },
        {
            id: 25,
            name: 'Michy',
            lastname: 'Batshuayi',
            number: 23,
            photo: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_410,q_auto,w_350/v1/editorial/people/on-loan/2017-18/headshot/Michy-Batshuayi',
            country: 'https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_18,q_auto/v1/site-assets/flags/BEL',
        }
    ]
}